#!/bin/bash

# WARNING: Ensure that "/bin/bash" is used instead of "/bin/sh"

WM_PROJECT_DIR=/opt/openfoam6
source $WM_PROJECT_DIR/etc/bashrc
echo "version: " && foamVersion

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/buildings.eMesh > /dev/null 2>&1
rm -f constant/polyMesh/boundary > /dev/null 2>&1

#------------------------------------------------------------------------------
