#!/bin/bash

# WARNING: Ensure that "/bin/bash" is used instead of "/bin/sh"

WM_PROJECT_DIR=/opt/openfoam6
source $WM_PROJECT_DIR/etc/bashrc
echo "version: " && foamVersion

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures

runApplication blockMesh
runApplication snappyHexMesh -overwrite

# NOTE: Necessary changes to allow proper use of dynamicRefineFvMesh!
# ------------------------------------------------------------------------------
    FILE_LIST=( "cellLevel" "pointLevel" )
    ORIGIN="0"
    DESTINATION="constant/polyMesh"

    for FILE in "${FILE_LIST[@]}"; do

        cp $ORIGIN/$FILE $DESTINATION/$FILE

        foamDictionary -entry FoamFile.class -set "labelList" $DESTINATION/$FILE
        foamDictionary -entry FoamFile.location -set "\"constant/polyMesh\"" $DESTINATION/$FILE
        foamDictionary -entry dimensions -remove $DESTINATION/$FILE
        foamDictionary -entry boundaryField -remove $DESTINATION/$FILE

        sed -i "s.internalField.//internalField.g" $DESTINATION/$FILE

    done
# ------------------------------------------------------------------------------

runApplication $(getApplication)

#------------------------------------------------------------------------------
